services:
  app:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
    environment:
      - MONGO_URI=mongodb://root:pass@db:27017/?authSource=admin
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
  db:
    image: mongo:latest
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=users
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass